### ISSUE TITLE
Result always outputs xml declaration

### ISSUE THREAD

**Issue by pft** [albanm/node-libxslt#12]
Regardless whether you have
```xml
  <xsl:output method="text" />
```
and/or 
```xml
  <xsl:output omit-xml-declaration="yes" />
```
there is always an xml declarion in the result string, which is not desired in those cases.

**Comment by albanm** [comment]
Can you try the same thing using xsltproc ? 

cf http://xmlsoft.org/XSLT/xsltproc2.html

**Comment by benoror** [comment]
xsltproc works as expected on x86_64 GNU/Linux:

```
[ec2-user@ip-172-31-37-169 xsltproc-test]$ xsltproc --version
Using libxml 20901, libxslt 10128 and libexslt 817
xsltproc was compiled against libxml 20901, libxslt 10128 and libexslt 817
libxslt 10128 was compiled against libxml 20901
libexslt 817 was compiled against libxml 20901
[ec2-user@ip-172-31-37-169 xsltproc-test]$ xsltproc xsl-w-decl.xsl input.xml
<?xml version="1.0"?>
<Entity>RIM_BPS</Entity>
[ec2-user@ip-172-31-37-169 xsltproc-test]$ xsltproc xsl-wo-decl.xsl input.xml
<Entity>RIM_BPS</Entity>
[ec2-user@ip-172-31-37-169 xsltproc-test]$
```

Test files: https://gist.github.com/benoror/4f83b2c05b85a95cbeae

**Comment by i-like-robots** [comment]
The `<xsl:output />` tag currently seems to be ignored entirely, for instance given:

```
<xsl:output method="html" encoding="UTF-8" indent="yes" omit-xml-declaration="yes" />
```

The output is XML (empty elements are self closed), has no formatting and includes the XML declaration.

**Comment by i-like-robots** [comment]
I have added a test case here (which are failing for me): https://github.com/i-like-robots/node-libxslt/commit/515e78aa902218244178ecc05eda05f2fa402e8e

My system:

```
OSX 10.10.3
Node 0.10.38
NPM 2.7.4
```

Also tried Node 0.12.4 but with the same result.

**Comment by i-like-robots** [comment]
My above comments may actually be null and void after all because this can be worked around. I think what's currently happening is technically correct albeit not intuitive.

```js
// If you pass in an XML document you get an XML document
var documentXML = libxslt.libxmljs.parseXml(document);

return parseFile('../stylesheets/article.xsl', function(err, stylesheet) {
	var transformedXML = stylesheet.apply(documentXML);

	//  We only want the (HTML) context, not the XML document as a whole
	return transformedXML.get('//root-element').toString();
});
```

**Comment by albanm** [comment]
Thanks for looking into it and sorry for the delay.

I just tried using your method (result.get(.).toString() instead of result.toString()) for serializing outputs. Unfortunately I don't seem to make it work without creating some regression in the case when there is no root element in the result.

If someone is willing to propose something, please feel free to submit a PR. The fix, if it is possible, should not be in the C++ code, but in the index.js file.

**Comment by i-like-robots** [comment]
I think the issue lies somewhere within the interface with libxmljs - I'll certainly spend some more time looking into it.

**Comment by neu-rah** [comment]
this happens because the xslt output is sent into a document, the wrapper MUST obtain a string or stream instead and deliver it to the consumer as is.
Any attempt to put the result in a document is subject to that document presumptions and will inherit a document xml declaration even if its not present on the original string

**Comment by pft** [comment]
@neu-rah I think you are right, when looking at `class ApplyWorker : public NanAsyncWorker` from node_libxslt.cc in tandem with `Stylesheet.prototype.apply` from index.js.

Note the following comment in both files:

    // for some obscure reason I didn't manage to create a new libxmljs document in applySync,
    // but passing a document by reference and modifying its content works fine

Definitely looks like the C++ code does need changing, sadly enough.

**Comment by neu-rah** [comment]
solved this locally added new function applyToString (with sync/assync mode)
seems to work fine

should i fork this repo or have to bind to this issue first?

**Comment by pft** [comment]
Good to hear that!

For the tests, you have to run `npm test` in the root folder. Of course, a test or two (with `omit-xml-declaration` and with `output="text"` or `output="html"` would be nice. I have no experience with Mocha either, but it does not seem so complicated from the looks of test/libxslt.js.

I think the best thing is to fork this repo, commit & push your work, then issue a pull request.

**Comment by gagern** [comment]
Looking at the xsltproc sources, if [output is directed to a file](https://git.gnome.org/browse/libxslt/tree/xsltproc/xsltproc.c?h=v1.1.28#n480), then xsltproc uses [`xsltRunStylesheetUser`](http://xmlsoft.org/XSLT/html/libxslt-transform.html#xsltRunStylesheetUser). For [output to stdout](https://git.gnome.org/browse/libxslt/tree/xsltproc/xsltproc.c?h=v1.1.28#n439), the [`xsltSaveResultToFile`](http://xmlsoft.org/XSLT/html/libxslt-xsltutils.html#xsltSaveResultToFile) function is used with stdout as an argument. There is also a [`xsltSaveResultToString`](http://xmlsoft.org/XSLT/html/libxslt-xsltutils.html#xsltSaveResultToString) and some [`xsltSaveResultTo`](http://xmlsoft.org/XSLT/html/libxslt-xsltutils.html#xsltSaveResultTo) which writes to an [`xmlOutputBuffer`](http://xmlsoft.org/html/libxml-tree.html#xmlOutputBuffer). The latter could probably be turned into a Node stream with some work, but the string version should be enough for our use case here.

**Comment by neu-rah** [comment]
i've tryed that user think also, the output is profiling information and profiling is done when a FILE* is not NULL

however xsltSaveResultToString seem to do the trick http://xmlsoft.org/XSLT/html/libxslt-xsltutils.html#xsltSaveResultToString

about apply http://xmlsoft.org/XSLT/html/libxslt-transform.html#xsltApplyStylesheet

> Apply the stylesheet to the document NOTE: This may lead to a non-wellformed output XML wise !

this seems to return an umparsed document (it can any format)... the libxslt is misleading here by using a document as return value

they should primarily return a string (as main method), we should gain performance when just outputting the result and flexibility as its not required to be xml derivate (I hope)

**Comment by neu-rah** [comment]
guess i don't need to change readme.md, right?

> *documented by [jsdoc-to-markdown](https://github.com/75lb/jsdoc-to-markdown)*.
