### ISSUE TITLE
Dependency on old libxmljs breaks install on iojs

### ISSUE THREAD

**Issue by webarnes** [albanm/node-libxslt#13]
This package depends on an old version of libxmljs that can't be built with iojs (and possibly node 0.12.x). There was a fix in libxmljs 0.14.1: see polotek/libxmljs#310

**Comment by albanm** [comment]
Can you try with the current master ?

I just accepted this PR https://github.com/albanm/node-libxslt/pull/11, we will point to a forked libxmljs (temporarily I hope) for memory management issues.
