### ISSUE TITLE
Adapt to nan 2

### ISSUE THREAD

**Issue by gagern** [albanm/node-libxslt#23]
In https://github.com/polotek/libxmljs/pull/330 libxmljs migrated to Nan 2, and in https://github.com/gagern/libxmljs/commit/f6c2c2f687049b32c30b1a7326d01ce3e12b037b libxmljs-mt followed suite. This is causing some build problems, as quite a number of Nan names have changed. I wonder whether it is safe to use Nan 1 and 2 in the same library, but probably wouldn't risk it. Instead I suggest node-libxslt be moved to Nan 2 as well. There is some `1to2.js` script hidden in the Nan directory tree, but so far I had found that thing caused more problems than it addressed.

**Comment by albanm** [comment]
I just tried the 1to2.js tool and get a bunch of errors.

I am not in a very brave mood, I guess I will wait for the migration guide: https://github.com/nodejs/nan/issues/402

**Comment by ChALkeR** [comment]
Adding to the list: https://github.com/nodejs/node/issues/2798.

**Comment by gagern** [comment]
https://nodesource.com/blog/cpp-addons-for-nodejs-v4 appears to be the official migration guide, suggesting `upgrade-utils` to automate large parts of the migration process. Haven't tried this yet. If someone wants to give this a shot, please do.

**Comment by gagern** [comment]
I made a stab at this, see #26. Users are welcome to try with various node versions and with real life applications. I make no guarantees at all.

**Comment by tornillo** [comment]
@albanm please bump the version of module with nan 2 to install it from npm.

**Comment by albanm** [comment]
Hello,

Sorry for not being very present. I am not in a good situation to work at home.

We had already talked about it, I just added you as contributor to this project and owner of the package on npm. Feel free to do what is necessary, I will catch up later.
