### ISSUE TITLE
node-libxslt.node: undefined symbol

### ISSUE THREAD

**Issue by MartijnR** [albanm/node-libxslt#25]
When using libxslt v0.5.4 _as a module of another module_ inside my app, I get a failure (in both node 0.10 and 0.12 on Ubuntu 14.04):

```
usr/bin/nodejs: symbol lookup error: /vagrant/node_modules/enketo-transformer/node_modules/libxslt/build/Release/node-libxslt.node: undefined symbol: _ZN8libxmljs12WorkerParentC1Ev
```

This failure does not occur when I perform the exact same transformation (same source, same stylesheet) in the module itself (where libxslt is a direct dependency and not a dependency of a dependency). Thus it seems to me that this may be an issue with path definitions inside node-libxslt.

This issue did not occur in 0.4.1.

I'll let you know if I find out more.

**Comment by MartijnR** [comment]
Thanks. I will check it out tomorrow. First, I'll see if the issue still persists. High on my todo list.

**Comment by MartijnR** [comment]
@gagern, Yes, you were spot on. I tested with libxslt 0.5.4 which has libxmljs-mt 0.14.3.

The mothership application included libxmljs 0.15.0 as well. This appeared to cause the conflict as you suggested.

I replaced that libxmljs module with libxmljs-mt version 0.14.3, and that resolved the issue. :+1: 

Too bad [this libxmljs issue](https://github.com/polotek/libxmljs/issues/296) doesn't seem to be progressing.

**Comment by gagern** [comment]
I think node-libxslt should export its libxmljs dependency, so that people could change their code like this:

```diff
-var libxmljs = require("libxmljs-mt");
 var libxslt = require("libxslt");
+var libxmljs = libxslt.libxmljs;
```

That way, people could be sure to use the same code at both levels, and avoid any funny problems. @albanm, what do you think about this? Should be real easy to do I believe.

**Comment by MartijnR** [comment]
I think it already does that, actually ;) https://github.com/albanm/node-libxslt#libxmljs-integration

**Comment by albanm** [comment]
Indeed it does !

**Comment by obujor** [comment]
I get the same Error:

> node_modules/libxslt/build/Release/node-libxslt.node: undefined symbol: _ZN8libxmljs12WorkerParentC1Ev
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings (/home/node/proxy/services/aknservicesfaonext/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/node/proxy/services/aknservicesfaonext/node_modules/libxslt/index.js:8:34)
    at Module._compile (module.js:570:32)

Any suggestions on how to fix it?
