### ISSUE TITLE
Core dumps - segmentation fault

### ISSUE THREAD

**Issue by neu-rah** [albanm/node-libxslt#38]
I've slimmed this issue down to this sample, its causing some weird core dumps when I do some xpath query to the document before delivering it to the xslt parser.
This is happening after some retries (150 on my machine), it looks like a leak.
can someone bring some light over it?

removing the  xmldoc.get("/") line it runs ok forever.

```javascript
"use strict";//with or without strict
var fs=require("fs");
var libxslt=require("libxslt");
var libxml=libxslt.libxmljs;
for(var cnt=0;cnt<10000;cnt++) {
  let xmldoc=libxml.parseXml(fs.readFileSync("template/@muf.xslt").toString());
  console.log(cnt);
  xmldoc.get("/");//removing this query (find or get) it runs ok
  let doc=libxslt.parse(xmldoc);
}
```

libxslt@0.6.0
node v4.2.3

**Comment by gagern** [comment]
Perhaps https://github.com/polotek/libxmljs/pull/365 fixes this. But the node memory management from https://github.com/polotek/libxmljs/commit/24f16a39d2ad454f37d611ffa0be7feeb3416c7c looks like it might interfere with asynchroneous operations, so I'll need to be careful when porting the latest version of libxmljs to my libxmljs-mt fork.

**Comment by neu-rah** [comment]
the work around for now is to parse twice and use one doc to load xslt and the other for the queries, as I have small xslt files and they cache => no big deal

**Comment by gagern** [comment]
https://github.com/gagern/libxmljs/commit/86c69f5bff56542d031ae3e3bda97476877bf9d6 includes [libxmljs v0.16.1](https://github.com/polotek/libxmljs/releases/tag/v0.16.1) but still segfaults. [The `Unref` call in the `~XmlNode` destructor](https://github.com/gagern/libxmljs/blob/86c69f5bff56542d031ae3e3bda97476877bf9d6/src/xml_node.cc#L442) references an invalid address, i.e. a different one than [the one used in the constructor](https://github.com/gagern/libxmljs/blob/86c69f5bff56542d031ae3e3bda97476877bf9d6/src/xml_node.cc#L243). The `doc` is the same but its `_private` is not. I see no `XmlDocument` actually setting that `_private` value. Strange! Needs further investigation.

**Comment by gagern** [comment]
The more I think about it, the more I feel like the doc-stealing from 771bf228f7dcb8c9279f4caea562aabe888c7eb9 is a more evil hack than I thought. The [`this->doc` document referenced in the destructor](https://github.com/gagern/libxmljs/blob/86c69f5bff56542d031ae3e3bda97476877bf9d6/src/xml_node.cc#L441-L442) is one such stolen document. Why its `_private` member is not `NULL` even though [`stealDocument` sets it to this](https://github.com/albanm/node-libxslt/blob/771bf228f7dcb8c9279f4caea562aabe888c7eb9/src/node_libxslt.cc#L25), I don't know yet. But it might be that libxslt uses the `_private` member for its own purpose, even though I haven't found that in the code yet.

It might make sense to move doc parsing into node-libxslt so we don't have to worry about who else might be referencing the document in question. Bah!
