### ISSUE TITLE
auto string wrapping can cause "XPath error : Invalid expression"

### ISSUE THREAD

**Issue by neu-rah** [albanm/node-libxslt#39]
This is a small patch

The auto string wrap commodity [here](https://github.com/albanm/node-libxslt/blob/master/index.js#L112-L115) can cause a XPath error if the parameter contains a xpath expression that uses ' (single quotes), ex:

    //*[@id='someid']

we can preserve the nice functionality but allow the second case to pass thru...
my suggestion: use options.noWrapParams (or something like it, please suggest name) to disable it in some cases.

when absent or =false on options the normal behavior is observed, must be explicit turned on

when turned on, the user is responsible to wrap the strings him self

its ok for params to be xpath expressions (naked strings) they will be evaluated and exist within the xslt as sets of nodes (very usefull)

this option extention would allow feeding xpath parameters but still disallows passing some xpath expressions as strings (in case we want the expression, not the node sets)

to allow passing xpath (and other data containing single quotes) i would sugest wrapping the parameters with double quotes instead avoiding escapping back and forth of xpath expressions

```javascript
if (!options.noWrapParams)
  for(var p in params) {
    // string parameters must be surrounded by quotes to be usable by the stylesheet
    if (typeof params[p] === 'string') params[p] = '"' + params[p].replace(/""/g,'\\"') + '"';
  }
```
with this litle change we can feed in xpath selectors and send xpath string expressions that use single quotes

I've also included an escape of double-quotes, is this ok or should we leave it to the user?

i can implement this if you guys agree

**Comment by albanm** [comment]
I am not sure I understand all the implications here. The best way to proceed in my opinion would be to submit a pull request with test cases illustrating all scenarios. The PR could or could not include a proposal of solution, the purpose is mainly to be very clear about the expected result.

Could you do this ?

**Comment by neu-rah** [comment]
yes i can, just wondering if someone could come up with better names or different implementation strategy.

**Comment by neu-rah** [comment]
on https://github.com/neu-rah/node-libxslt
1 - dropped  .replace(/""/g,'\\"') as it was not working as i thought initially
2 - using double quotes to wrap instead of single quotes, guess i could use double-quotes on my xpath instead of single and avoid this, however xpath examples are all single-quoted, no? we can have an option to specify the wrapping character, is it a better idea?
3 - wrapping can be explicitly disabled with options.noWrapParams, otherwise we can not pass xpath expressions, also when reusing the options object, prams will get re-wrapped

**Comment by albanm** [comment]
Thanks !
