### ISSUE TITLE
Build error, missing file: xmljs.node

### ISSUE THREAD

**Issue by azatoth** [albanm/node-libxslt#41]
Tried to install libxslt but it sadly failed during building; See npm log for more information. 
Relevant error is

```
  SOLINK_MODULE(target) Release/obj.target/node-libxslt.node
g++: error: /home/azatoth/Project/eaktiebok/node_modules/libxmljs-mt/build/Release/xmljs.node: No such file or directory
node-libxslt.target.mk:136: recipe for target 'Release/obj.target/node-libxslt.node' failed
```

I installed libxmljs-mt manually to see, and I notice there is a xmljs.node file in either lib.target/ or obj.target/ in the Release dir.
[npm-debug.log.txt](https://github.com/albanm/node-libxslt/files/74722/npm-debug.log.txt)

**Comment by Nabrok** [comment]
Having the same error, any solutions?

**Comment by rainabba** [comment]
ditto

**Comment by rainabba** [comment]
Back to this again :(  Doesn't seem to happen with NPM 4.6.1, but only 5.x.x and it's the ONLY packages I'm having any issues with are libxslt and libxmljs-mt (due to libxslt I believe). Not sure what to make of it other than the build is failing and the failure isn't getting caught well enough for my eyes to find.

**Comment by gagern** [comment]
I recently changed libxmljs-mt to also use precompiled binaries. Can you give that a try?

**Comment by Sojourneer** [comment]
I have this problem.
I don't believe precompiled binaries will work, as I am using mup to deploy my meteor project.

**Comment by Nabrok** [comment]
Sojourneer ... I'm not having this issue any more, are you using up to date versions of npm, node, etc?

**Comment by Sojourneer** [comment]
I am using from meteor. When I tried to update meteor, everything broke, so I would like to avoid making big changes for what seems to be a build misconfiguration.

**Comment by lognaturel** [comment]
There seems to be a similar issue with npm 7, tracked at https://github.com/npm/cli/issues/3556
