### ISSUE TITLE
Turn off the XML def header from JSON response

### ISSUE THREAD

**Issue by vish91** [albanm/node-libxslt#57]
Hi everyone, 

Is there an option to turn off the XML def Header from the JSON response ? 
I parse my document and applu stylesheet on document to get this result: 
Eg. 
`<?xml version="1.0" encoding="UTF-8"?>`
{
    "foreignKey": "key1",
    "title": "Title1",
    "description": "Som text..."
}

I do not want a XML header in my JSON transformed response. Can I turn it off with some option ??

**Comment by albanm** [comment]
I am not sure I understand your situation. You have a JSON serialized as the result the xslt transform ?

Have a look at [example.js](./example.js) for example. It doesn't produce a xml header in the output.

**Comment by vish91** [comment]
Hey, sorry if I was not clear. 
Yes, I am trying to generate build the JSON by substituting the params in the xsl from the xml file.
Once I transform it , I need the serialized JSON for furthur processing. 
But, the transformation gives me a result of sort: 
`<?xml version="1.0" encoding="UTF-8"?>`
{
"foreignKey": "key1",
"title": "Title1",
"description": "Som text..."
}
which I cannot parse directly as JSON because of the XML declaration that the result object has. 
i.e.
```
     var stylesheetObj = libxmljs.parseXml(xsltString, { nocdata: true });
      var stylesheet = libxslt.parse(stylesheetObj);
    
      console.log("This is xml body: " +xmlBody);
      var document = libxmljs.parseXml(xmlBody);
    
       var result = stylesheet.apply(document);
        // result is now a libxmljs document containing the result of the transformation
        console.log("Transformed XSLT to StyleSheet" + result);
```

So, all I need is to know if there is an option in the `apply` function to stop giving back the xml declaration. Or if the apply function should have handled it as I have it specified in the xslt `<xsl:output method="text" omit-xml-declaration="yes"/>` and it still returns me the declaration in output result.

**Comment by albanm** [comment]
Ok, it took me a while to remember, but yes actually the omit-xml-declaration should be respected. It is covered by the tests here: https://github.com/albanm/node-libxslt/blob/master/test/libxslt.js#L204

So I don't understand what is different for you. The libxmljs you use was required separately ? If so you could try using the one exposed by libxlst, cf the readme: 

> The libxmljs module required by node-libxslt is exposed as require('libxslt').libxmljs. This prevents depending on libxmljs twice which is not optimal and source of weird bugs.

Actually in your example you could do without libxmljs, as the libxslt.parse and stylesheet.apply functions accept text as well as xml docs.

**Comment by albanm** [comment]
Ok, I remember now. If you pass an xml doc to apply() you will get an xml doc in return, and an xml doc will be serialized with the header. If you want a text return you should pass the document as a string, in this case the return is a string and the header will not be forced on you.

**Comment by vish91** [comment]
That worked out fine. Changed the input to `parse` and `apply` functions to be `String` and that fixed the problem, don't see the header any longer. 
Didn't see any examples where the input was being parsed from String, I guess all examples work with reading from Files, so I did not catch this from doc or README.
``` var stylesheet = libxslt.parse(xsltString);
      var result = stylesheet.apply(xmlString);
      // result is now a String document containing the result of the transformation
      console.log("Transformed XSLT to StyleSheet" + result);
```  
Very cool. I will close this issue. Thank you.
