### ISSUE TITLE
Can't install using NPM 5.0.1

### ISSUE THREAD

**Issue by rainabba** [albanm/node-libxslt#59]
Below is the most relevant bit, but I've also attached the full NPM log.

> 108 verbose lifecycle libxslt@0.6.5~install: CWD: C:\PRJ\AZPREP\GIT\WEB\BatchManWeb\node_modules\libxslt
> 109 silly lifecycle libxslt@0.6.5~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
> 110 silly lifecycle libxslt@0.6.5~install: Returned: code: 1  signal: null
> 111 info lifecycle libxslt@0.6.5~install: Failed to exec install script
> 112 verbose unlock done using C:\Users\username\AppData\Roaming\npm-cache\_locks\staging-99c8fbd337195d0a.lock for C:\PRJ\AZPREP\GIT\WEB\BatchManWeb\node_modules\.staging
> 113 verbose stack Error: libxslt@0.6.5 install: `node-gyp rebuild`
> 113 verbose stack Exit status 1
> 113 verbose stack     at EventEmitter.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:283:16)
> 113 verbose stack     at emitTwo (events.js:106:13)
> 113 verbose stack     at EventEmitter.emit (events.js:191:7)
> 113 verbose stack     at ChildProcess.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
> 113 verbose stack     at emitTwo (events.js:106:13)
> 113 verbose stack     at ChildProcess.emit (events.js:191:7)
> 113 verbose stack     at maybeClose (internal/child_process.js:886:16)
> 113 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> 114 verbose pkgid libxslt@0.6.5
> 115 verbose cwd C:\PRJ\AZPREP\GIT\WEB\BatchManWeb
> 116 verbose Windows_NT 10.0.15063
> 117 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "libxslt@0.6.5" "--save"
> 118 verbose node v6.10.3
> 119 verbose npm  v5.0.1
> 120 error code ELIFECYCLE
> 121 error errno 1
> 122 error libxslt@0.6.5 install: `node-gyp rebuild`
> 122 error Exit status 1
> 123 error Failed at the libxslt@0.6.5 install script.
> 123 error This is probably not a problem with npm. There is likely additional logging output above.
> 124 verbose exit [ 1, true ]
>

**Comment by ankon** [comment]
As you're using npm@5: this is actually an npm issue, see https://github.com/npm/npm/issues/16824

**Comment by rainabba** [comment]
Makes sense. Feel free to close and I'll follow that one.

**Comment by rainabba** [comment]
I believe this is resolved with NPM 5.0.3
