### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by luastoned** [albanm/node-libxslt#60]
After just importing this library my app gets stuck, i'm using react with webpack.

Here is the warning/error:
```
WARNING in ./node_modules/bindings/bindings.js
76:22-40 Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/bindings/bindings.js
76:43-53 Critical dependency: the request of a dependency is an expression

node --version
v8.0.0

yarn --version
0.27.5
```

I'm on Windows 10 x64

**Comment by albanm** [comment]
Webpack allows you require any npm module, but not all of them will work in any context. This module uses native extensions for nodejs and is for nodejs only, not the browser.

**Comment by luastoned** [comment]
Thanks for the headsup, I do plan on using it in the backend.
