### ISSUE TITLE
0.7.0 unable to build on windows (node 6.10) vsaprintf missing on windows

### ISSUE THREAD

**Issue by arisbasic** [albanm/node-libxslt#64]
vsaprintf is missing on windows and it stops 0.7.0
from building

**Comment by gmarab** [comment]
The same for me on Windows Server 2012, Node 8.7.0.
The 0.6.5 version work.

**Comment by rainabba** [comment]
Ditto on Win 10, Node 6.10.3 and NPM 4.6.1 (can't use NPM 5.x because of other broken packages)

**Comment by albanm** [comment]
Yes, sorry about that !

I need to fix this soon, in the meantime please use version 0.6.5.

**Comment by rainabba** [comment]
Time to move on to Node 8.x and now 0.6.5 and 0.7.0 fail to build. I'm looking to see if anyone has posted this issue, but I wanted to update here in case it's that this issue was never resolved.

**Comment by fhuttere** [comment]
Any update on this? 0.7.0 remains unusable on Windows.
