### ISSUE TITLE
Internal error in xsltCopyText(): Failed to copy the string.

### ISSUE THREAD

**Issue by yacinlahmidi** [albanm/node-libxslt#67]
Hello,
We would like to report a possible issue in the library :
We are trying to apply an XSL to a XML file.
This XML file has an attribute containing a big picture in Base 64 (about 2 megabytes).

> runtime error: element text
xsltCopyText: text allocation failed
runtime error: element text
xsltCopyText: text allocation failed
runtime error: element text
xsltCopyText: text allocation failed
runtime error: element text
xsltCopyText: text allocation failed
runtime error: element text
xsltCopyText: text allocation failed
runtime error: element text
xsltCopyText: text allocation failed
runtime error: element text
xsltCopyText: text allocation failed
runtime error: element text
xsltCopyText: text allocation failed
runtime error: element text
xsltCopyText: text allocation failed
runtime error: element text
xsltCopyText: text allocation failed
runtime error: element text
xsltCopyText: text allocation failed
runtime error: element text
xsltCopyText: text allocation failed
runtime error: element text
xsltCopyText: text allocation failed
runtime error: element text
xsltCopyText: text allocation failed
runtime error: element text
xsltCopyText: text allocation failed
runtime error: element text
xsltCopyText: text allocation failed
runtime error: element text
xsltCopyText: text allocation failed
runtime error: element text
xsltCopyText: text allocation failed
runtime error: element text
xsltCopyText: text allocation failed
runtime error
Internal error in xsltCopyText(): Failed to copy the string.

**Comment by albanm** [comment]
Hello,

Please try to apply the same transformation using [xsltproc](http://xmlsoft.org/XSLT/xsltproc.html).

If you have the same errors then the issue is not with this nodejs wrapper but with the original libxslt library.
