### ISSUE TITLE
make: g++ not found - libxmljs-mt

### ISSUE THREAD

**Issue by belfour** [albanm/node-libxslt#70]
HI,

Node v8.12.0, NPM v6.4.1

make: Entering directory '/home/project/node_modules/libxmljs-mt/build'
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
make: g++: Command not found
xmljs.target.mk:165: recipe for target 'Release/obj.target/xmljs/src/libxmljs.o' failed
make: *** [Release/obj.target/xmljs/src/libxmljs.o] Error 127
make: Leaving directory '/home/project/node_modules/libxmljs-mt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/steve/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-33-generic

**Comment by ankon** [comment]
g++ is supposed to be installed on your system -- typically using whatever software management approach you use. You're looking for something called 'GNU C/C++ Compiler'.

**Comment by belfour** [comment]
@ankon - Working now.  I can't thank you enough!
