### ISSUE TITLE
Libxslt Browser Usage 

### ISSUE THREAD

**Issue by ucalis** [albanm/node-libxslt#71]
I am trying to use libxslt in web application ( running on browser) .  I got error about requiring your library.  I am faced with a kind of TypeError.  Does it have browser support ? Or is it impossible using in web application ? I am also using npm 6.14.4 version, not latest one.  Do I need to use newer npm version ?

**Comment by ankon** [comment]
Libxslt is a thin wrapper around a native library (called libxslt!), so it won’t work in a browser. 

But: a browser already provides XSL transformation support, so you shouldn’t need an additional library.
