### ISSUE TITLE
Unhandled asynchronous exception: TypeError: binding.registerEXSLT is not a function

### ISSUE THREAD

**Issue by A1M918** [albanm/node-libxslt#75]
Hi, 

So I have been using this for years. But after upgrading my node version from `8.16.1`  -> `12.16.1` it gives me following error as soon as I run the project. 
```
Unhandled asynchronous exception: TypeError: binding.registerEXSLT is not a function
    at Object.<anonymous> (path/to/my/project/node_modules/libxslt/index.js:10:9) 
```

I already read this thread [here](https://github.com/albanm/node-libxslt/issues/68) but this error is new I believe.

Node version : 12.16.1
OS Ubuntu 18 LTS
Package manager : yarn

**Comment by albanm** [comment]
Hi,

I don't actively maintain this repo anymore, I simply accept necessary pull requests. You could try to fix this yourself, or maybe contact the persons that worked on fixing the node 10 incompatibilities.
