### ISSUE TITLE
Cant install libxslt

### ISSUE THREAD

**Issue by venugee** [albanm/node-libxslt#78]
Output:
node-pre-gyp http GET https://github.com/gagern/libxmljs/releases/download/v1.0.0-mt/node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Completion callback never invoked!
node-pre-gyp ERR! System Windows_NT 10.0.17763
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\n1528034\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
node-pre-gyp ERR! cwd C:\Users\n1528034\node_modules\node1-libxmljsmt
node-pre-gyp ERR! node -v v10.19.0
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>

**Comment by ncub8** [comment]
Here is my log of the same issue running on Mac

node1-libxmljsmt@1.0.0 install /Users/johnmoore/work/test/node_modules/node1-libxmljsmt
> node-pre-gyp install --fallback-to-build --loglevel http

node-pre-gyp http GET https://github.com/gagern/libxmljs/releases/download/v1.0.0-mt/node-v64-darwin-x64.tar.gz
node-pre-gyp http 404 https://github.com/gagern/libxmljs/releases/download/v1.0.0-mt/node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/gagern/libxmljs/releases/download/v1.0.0-mt/node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node1-libxmljsmt@1.0.0 and node@10.13.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/gagern/libxmljs/releases/download/v1.0.0-mt/node-v64-darwin-x64.tar.gz 
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /opt/anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:381:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close (net.js:606:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--loglevel=http" "--module=/Users/johnmoore/work/test/node_modules/node1-libxmljsmt/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/Users/johnmoore/work/test/node_modules/node1-libxmljsmt/build/Release" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /Users/johnmoore/work/test/node_modules/node1-libxmljsmt
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --loglevel=http --module=/Users/johnmoore/work/test/node_modules/node1-libxmljsmt/build/Release/xmljs.node --module_name=xmljs --module_path=/Users/johnmoore/work/test/node_modules/node1-libxmljsmt/build/Release --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/johnmoore/work/test/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/johnmoore/work/test/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
node-pre-gyp ERR! cwd /Users/johnmoore/work/test/node_modules/node1-libxmljsmt
node-pre-gyp ERR! node -v v10.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --loglevel=http --module=/Users/johnmoore/work/test/node_modules/node1-libxmljsmt/build/Release/xmljs.node --module_name=xmljs --module_path=/Users/johnmoore/work/test/node_modules/node1-libxmljsmt/build/Release --napi_version=3 --node_abi_napi=napi' (1)
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node1-libxmljsmt@1.0.0 install: `node-pre-gyp install --fallback-to-build --loglevel http`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node1-libxmljsmt@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/johnmoore/.npm/_logs/2020-11-13T15_21_35_255Z-debug.log
(base) Johns-MBP:test johnmoore$

**Comment by vckeating** [comment]
Here are my logs for the same issue, Windows 10:

C:\Users\vkeating\Apps\work\test>npm i libxslt

> node1-libxmljsmt@1.0.0 install C:\Users\vkeating\Apps\work\test\node_modules\node1-libxmljsmt
> node-pre-gyp install --fallback-to-build --loglevel http

node-pre-gyp http GET https://github.com/gagern/libxmljs/releases/download/v1.0.0-mt/node-v64-win32-x64.tar.gz
node-pre-gyp http 404 https://github.com/gagern/libxmljs/releases/download/v1.0.0-mt/node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/gagern/libxmljs/releases/download/v1.0.0-mt/node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node1-libxmljsmt@1.0.0 and node@10.15.3 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/gagern/libxmljs/releases/download/v1.0.0-mt/node-v64-win32-x64.tar.gz
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\vkeating\AppData\Local\Programs\Python\Python38\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--loglevel=http" "--module=C:\\Users\\vkeating\\Apps\\work\\test\\node_modules\\node1-libxmljsmt\\build\\Release\\xmljs.node" "--module_name=xmljs" "--module_path=C:\\Users\\vkeating\\Apps\\work\\test\\node_modules\\node1-libxmljsmt\\build\\Release" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd C:\Users\vkeating\Apps\work\test\node_modules\node1-libxmljsmt
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --loglevel=http --module=C:\Users\vkeating\Apps\work\test\node_modules\node1-libxmljsmt\build\Release\xmljs.node --module_name=xmljs --module_path=C:\Users\vkeating\Apps\work\test\node_modules\node1-libxmljsmt\build\Release --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\vkeating\Apps\work\test\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Windows_NT 10.0.17763
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\vkeating\\Apps\\work\\test\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
node-pre-gyp ERR! cwd C:\Users\vkeating\Apps\work\test\node_modules\node1-libxmljsmt
node-pre-gyp ERR! node -v v10.15.3
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --loglevel=http --module=C:\Users\vkeating\Apps\work\test\node_modules\node1-libxmljsmt\build\Release\xmljs.node --module_name=xmljs --module_path=C:\Users\vkeating\Apps\work\test\node_modules\node1-libxmljsmt\build\Release --napi_version=3 --node_abi_napi=napi' (1)
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\vkeating\Apps\work\test\package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node1-libxmljsmt@1.0.0 install: `node-pre-gyp install --fallback-to-build --loglevel http`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node1-libxmljsmt@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vkeating\AppData\Roaming\npm-cache\_logs\2020-11-13T16_48_03_379Z-debug.log

**Comment by qq240814476** [comment]
node: 12.16.2

node-pre-gyp http GET https://github.com/gagern/libxmljs/releases/download/v0.18.3-mt/node-v72-darwin-x64.tar.gz
node-pre-gyp http 404 https://github.com/gagern/libxmljs/releases/download/v0.18.3-mt/node-v72-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/gagern/libxmljs/releases/download/v0.18.3-mt/node-v72-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for libxmljs-mt@0.18.3 and node@12.16.2 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/gagern/libxmljs/releases/download/v0.18.3-mt/node-v72-darwin-x64.tar.gz 
node-pre-gyp ERR! Tried to download(undefined): https://github.com/gagern/libxmljs/releases/download/v0.18.3-mt/node-v72-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for libxmljs-mt@0.18.3 and node@12.16.2 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http Connection closed while downloading tarball file 
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.


No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.


No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.


gyp: No Xcode or CLT version detected!
gyp: No Xcode or CLT version detected!
gypgyp ERR! configure error 
 ERR!gyp  configure error 
ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/bytedance/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp gyp ERR! ERR!System  Darwin 19.6.0
stackgyp Error: `gyp` failed with exit code: 1
 gypERR!  command "/Users/bytedance/.nvm/versions/node/v12.16.2/bin/node" "/Users/bytedance/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--loglevel=http" "--module=/Users/bytedance/code/work-space/em-api-latex_export/node_modules/libxmljs-mt/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/Users/bytedance/code/work-space/em-api-latex_export/node_modules/libxmljs-mt/build/Release"
ERR! stackgyp      at ChildProcess.onCpExit (/Users/bytedance/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
ERR!gyp  cwd /Users/bytedance/code/work-space/em-api-latex_export/node_modules/libxmljs-mt
ERR!gyp  ERR!stack node -v     at ChildProcess.emit (events.js:310:20)
 v12.16.2
gypgyp  ERR!ERR!  node-gyp -vstack v5.1.0
     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! not ok 
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/bytedance/.nvm/versions/node/v12.16.2/bin/node" "/Users/bytedance/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--loglevel=http" "--module=/Users/bytedance/code/work-space/em-api-latex_export/node_modules/libxmljs-mt/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/Users/bytedance/code/work-space/em-api-latex_export/node_modules/libxmljs-mt/build/Release"
gyp ERR! cwd /Users/bytedance/code/work-space/em-api-latex_export/node_modules/libxmljs-mt
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/bytedance/.nvm/versions/node/v12.16.2/bin/node /Users/bytedance/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --loglevel=http --module=/Users/bytedance/code/work-space/em-api-latex_export/node_modules/libxmljs-mt/build/Release/xmljs.node --module_name=xmljs --module_path=/Users/bytedance/code/work-space/em-api-latex_export/node_modules/libxmljs-mt/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/bytedance/code/work-space/em-api-latex_export/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Darwin 19.6.0
node-pre-gyp ERR! command "/Users/bytedance/.nvm/versions/node/v12.16.2/bin/node" "/Users/bytedance/code/work-space/em-api-latex_export/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
node-pre-gyp ERR! cwd /Users/bytedance/code/work-space/em-api-latex_export/node_modules/libxmljs-mt
node-pre-gyp ERR! node -v v12.16.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/Users/bytedance/.nvm/versions/node/v12.16.2/bin/node /Users/bytedance/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --loglevel=http --module=/Users/bytedance/code/work-space/em-api-latex_export/node_modules/libxmljs-mt/build/Release/xmljs.node --module_name=xmljs --module_path=/Users/bytedance/code/work-space/em-api-latex_export/node_modules/libxmljs-mt/build/Release' (1)
npm WARN enoent ENOENT: no such file or directory, open '/Users/bytedance/code/work-space/em-api-latex_export/node_modules/sane/node_modules/cross-spawn/package.json'
npm WARN em.api.latex_export@1.0.0 No repository field.

**Comment by ankon** [comment]
> gyp ERR! stack Error: Command failed: /opt/anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];

@ncub8: This seems it is picking up some odd python version. Might be an issue with your PATH / might be fixable by making sure that the system python is found first.

**Comment by ankon** [comment]
> No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
> No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
> 
> No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
> No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
> 
> No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
> No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
> 
> gyp: No Xcode or CLT version detected!
> gyp: No Xcode or CLT version detected!

@qq240814476 it looks like you do not have the required tools installed to actually compile something from source.
