### ISSUE TITLE
libxslt package.json is not node-pre-gyp ready:

### ISSUE THREAD

**Issue by brandonros** [albanm/node-libxslt#88]
#13 0.804 node-pre-gyp ERR! stack Error: libxslt package.json is not node-pre-gyp ready:
#13 0.805 node-pre-gyp ERR! stack package.json must declare these properties:
#13 0.807 node-pre-gyp ERR! stack binary.module_name
#13 0.808 node-pre-gyp ERR! stack binary.module_path
#13 0.820 node-pre-gyp ERR! stack binary.host

**Comment by lognaturel** [comment]
This has something to do with your environment. https://stackoverflow.com/a/57862667 Is an example of troubleshooting this kind of error. If that doesn’t help, Stackoverflow would be a great place to post more details about the issue. You’ll need to include your node version, etc.
